//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERGIA_PACIENTE
    {
        public string CEDULA_P { get; set; }
        public string CEDULA_M { get; set; }
        public string NOMBRE_ALERGIA { get; set; }
        public System.DateTime FECHA_DIAGNOSTICO { get; set; }
        public string MEDICAMENTOS { get; set; }
        public int ID { get; set; }
    
        public virtual ALERGIA ALERGIA { get; set; }
        public virtual MEDICO MEDICO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
