//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITA
    {
        public string CEDULA_P { get; set; }
        public string CENTRO_SALUD { get; set; }
        public System.DateTime FECHA_H { get; set; }
        public string ESPECIALIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public string CEDULA_M { get; set; }
        public int ID { get; set; }
    
        public virtual MEDICO MEDICO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
